---
apiVersion: v1
kind: Namespace
metadata:
  name: message-server
---
apiVersion: v1
kind: Secret
metadata:
  name: message-server
  namespace: message-server
data:
  pg_endpoint: cG9zdGdyZXNxbDovL215dXNlcjpXZWxjb21lMTIzQDE5Mi4xNjguNjQuNDYvbWVzc2FnZXMK
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-server
  namespace: message-server
data:
  pg_endpoint: "postgresql://myuser:Welcome123@192.168.64.46/messages"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-server
  namespace: message-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-server
  template:
    metadata:
      labels:
        app: message-server
    spec:
      containers:
      - name: message-server
        image: sylesh687/message-server:latest
        env:
        - name: SQLALCHEMY_DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: message-server
              key: pg_endpoint
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: message-server
  namespace: message-server
spec:
  type: NodePort
  selector:
    app: message-server
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80
      nodePort: 30007


