---
apiVersion: v1
kind: Namespace
metadata:
  name: message-server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: message-server
  labels:
    app: postgres
data:
  POSTGRES_DB: messages
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: Welcome123
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  namespace: message-server
  labels:
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: message-server
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: message-server
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-pv-claim
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-pv-claim
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: message-server
  namespace: message-server
data:
  username: "bXl1c2VyCg=="
  password: "V2VsY29tZTEyMwo="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-server
  namespace: message-server
data:
  db_url: "192.168.64.41"
  db_name: "messages"
---

